name: Verify

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.7
      - run: bundle install
      - name: Rubocop
        run: rubocop
      - name: Rspec
        run: bundle exec rspec